# Automates cleaning and build cycles for ProjectInitializer program.
#
# Author: Alexander Roth
# Date:   2015-01-06

.PHONY: compile
compile:
	javac *.java

.PHONY: clean
clean:
	rm -f *~ *.class

.PHONY: all
all: clean compile
